# Generated by Django 4.2.1 on 2023-07-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0002_alter_blogpost_post_sub_alter_galerymodel_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderaddress',
            name='area',
            field=models.CharField(choices=[('first area', '1st Area'), ('second area', '2nd Area'), ('third area', '3rd Area'), ('fourth area', '4th Area'), ('fifth area', '5th Area'), ('sixth area', '6th Area'), ('seventh area', '7th Area'), ('eighth area', '8th Area'), ('ninth area', '9th Area'), ('tenth area', '10th Area'), ('eleventh area', '11th Area'), ('twelfth  area', '12th Area'), ('thirteenth  area', '13th Area'), ('fourteenth  area', '14th Area'), ('fifteenth  area', '15th Area'), ('sixteenth  area', '16th Area')], max_length=128),
        ),
    ]
